## Numpy In Action

In [10]:
import numpy as np
import pandas as pd

In [3]:
# Create a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [4]:
massive_array[:10]

array([0.07483897, 0.9288597 , 0.35280725, 0.88371341, 0.18992264,
       0.42432798, 0.77808375, 0.53634376, 0.79721774, 0.25235195])

In [5]:
# compariing numpy sum and python sum

%timeit sum(massive_array) # Python's sum
%timeit np.sum(massive_array) # NumPy's sum 

16.5 ms ± 316 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
92.6 µs ± 2.6 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [6]:
# 16815 for python
# 95.2 for numpy


In [7]:
16815/95.2

176.62815126050418

In [8]:
# Numpy is 176.62815126050418 faster

## Nut butter sales

In [11]:
# generating a random data for sales amount
np.random.seed(0)
sales_amounts = np.random.randint (20, size = (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [12]:
# labelling rows and columns 
weekly_sales = pd.DataFrame(sales_amounts, index =["Mon", "Tues", "Wed", "Thurs", "Fri"], columns = ["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [14]:
# create prices array
prices = np.array([10, 8, 12])
prices.shape

(3,)

In [15]:
# creating butter prices


butter_prices = pd.DataFrame (prices.reshape(1,3),  index = ["price"], columns = ["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
price             10              8             12

In [16]:
#dot product (.dot())
Total = sales_amounts.dot(prices.T)
Total

array([240, 138, 458, 232, 142])

In [17]:
#creatingdaily_sales
weekly_sales.T

Mon  Tues  Wed  Thurs  Fri
Almond butter   12     3    9      4    1
Peanut butter   15     3   19      6    6
Cashew butter    0     7   18     12    7

In [18]:
butter_prices.shape

(1, 3)

In [20]:
daily_sales=  butter_prices.dot(weekly_sales.T)

In [21]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales


Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

In [22]:
## Turn images to numpy array

<img src="me.png"/>

In [27]:
from matplotlib.image import imread

me = imread("me.png")
type(me)

numpy.ndarray

In [28]:
me.shape, me.size, me.ndim

((1024, 823, 3), 2528256, 3)

In [29]:
me

array([[[0.03529412, 0.00392157, 0.        ],
        [0.03529412, 0.00392157, 0.        ],
        [0.03137255, 0.        , 0.        ],
        ...,
        [0.02745098, 0.02352941, 0.00784314],
        [0.02745098, 0.02352941, 0.00784314],
        [0.02745098, 0.02352941, 0.00784314]],

       [[0.31764707, 0.22745098, 0.15686275],
        [0.31764707, 0.22745098, 0.15686275],
        [0.3137255 , 0.22352941, 0.15294118],
        ...,
        [0.14509805, 0.14117648, 0.1254902 ],
        [0.14509805, 0.14117648, 0.1254902 ],
        [0.14509805, 0.14117648, 0.1254902 ]],

       [[0.56078434, 0.35686275, 0.16078432],
        [0.5568628 , 0.3529412 , 0.15686275],
        [0.5529412 , 0.34901962, 0.15294118],
        ...,
        [0.13725491, 0.13333334, 0.11764706],
        [0.13725491, 0.13333334, 0.11764706],
        [0.13725491, 0.13333334, 0.11764706]],

       ...,

       [[0.47058824, 0.29803923, 0.05882353],
        [0.47058824, 0.29803923, 0.05882353],
        [0.47058824, 0